esphome:
    name: http-client
    comment: I'm too lazy to do http request
    platform: ESP8266
    board: d1_mini
http_request:
  useragent: esphome/device
  timeout: 30s
wifi:
  ssid: Mujahed
  password: 050519800
binary_sensor:
  - platform: gpio
    pin: 
      number: D3
      mode: INPUT_PULLUP
    name: "Push Button"
    filters:
      - delayed_on: 1s
    on_state:
      - logger.log: "Switch Pressed"
      - http_request.get:
          url: http://192.168.1.200/?dev_id=wemosd1
          on_response:
              - logger.log:
                  format: 'Response status: %d'
                  args:
                    - status_code
logger:
  level: INFO
api:
web_server:
  port: 8080
captive_portal:
